# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: faa92fd7fedeef53007a987abd5cf2f2887377846316c129916105baea17ebdb00020ae4646fa6d28894db570c55c22c0ac2698095d68022b710eff440c55733

test:
  secret_key_base: 75af32dbeb792998813a37d7bcd64bed116b591f124af0c3efef00ffd19811b021d7ce81bb94e7993f9a7ee2a8b6d1e5677d54aba2977950a821b83445ce70ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
